Allow disabling of connection test

diff --git a/deploy/deploy b/deploy/deploy
--- a/deploy/deploy
+++ b/deploy/deploy
@@ -50,24 +50,30 @@ SKIP_CF_STABLE_HELM_REPO=true \
 WAIT=true \
 /opt/bin/release_chart
 
-env ACTION=auth \
-SKIP_CF_STABLE_HELM_REPO=true \
-HELM_VERSION=$helm_version \
-CHART_VERSION=$chart_version \
-KUBE_CONTEXT=$KUBE_CONTEXT \
-/opt/bin/release_chart
-helm test $NAMESPACE --namespace $NAMESPACE
+TEST_CONNECTION=${TEST_CONNECTION:-true}
+if [[ "$TEST_CONNECTION" = true ]];
+then
+  env ACTION=auth \
+  SKIP_CF_STABLE_HELM_REPO=true \
+  HELM_VERSION=$helm_version \
+  CHART_VERSION=$chart_version \
+  KUBE_CONTEXT=$KUBE_CONTEXT \
+  /opt/bin/release_chart
+  helm test $NAMESPACE --namespace $NAMESPACE
 
-helm_test_status=$(kubectl get pods --selector="app.kubernetes.io/managed-by=Helm" -o jsonpath='{.items[?(@.status.phase!="Succeeded")].status.phase}' --cluster $KUBE_CONTEXT --namespace $NAMESPACE)
-if [[ "$helm_test_status" == "Failed" ]]; then
-  echo "ERROR: The branch has not passed because the Helm Test failed, please check your application pod.";
-  exit 1;
+  helm_test_status=$(kubectl get pods --selector="app.kubernetes.io/managed-by=Helm" -o jsonpath='{.items[?(@.status.phase!="Succeeded")].status.phase}' --cluster $KUBE_CONTEXT --namespace $NAMESPACE)
+  if [[ "$helm_test_status" == "Failed" ]]; then
+    echo "ERROR: The branch has not passed because the Helm Test failed, please check your application pod.";
+    exit 1;
+  else
+    # It is necessary to remove the test pod from the helm test bacause HPA metrics may fail when we have a pod with completed status.
+    # Issue: https://github.com/kubernetes/kubernetes/issues/79365
+    # Issues: https://github.com/kubernetes/kubernetes/issues?page=1&q=is%3Aissue+is%3Aopen+HPA
+    echo "INFO: Removed the completed Test Pod";
+    kubectl delete pod --selector="app.kubernetes.io/managed-by=Helm" --namespace $NAMESPACE
+  fi
 else
-  # It is necessary to remove the test pod from the helm test bacause HPA metrics may fail when we have a pod with completed status.
-  # Issue: https://github.com/kubernetes/kubernetes/issues/79365
-  # Issues: https://github.com/kubernetes/kubernetes/issues?page=1&q=is%3Aissue+is%3Aopen+HPA
-  echo "INFO: Removed the completed Test Pod";
-  kubectl delete pod --selector="app.kubernetes.io/managed-by=Helm" --namespace $NAMESPACE
+  echo "Connection test is disabled.";
 fi
 
 cf_export NAMESPACE=re-$SHORT_NAME-$HASH
