fix: change bash to -e so code 1 will not exit execution

diff --git a/src/deploy/deploy b/src/deploy/deploy
--- a/src/deploy/deploy
+++ b/src/deploy/deploy
@@ -1,6 +1,6 @@
 #!/bin/bash
-# exit if any command fails
-set -e
+# overrides default `set -e`: Do not exit if a command fails.
+set +e
 
 verbose=${KR_VERBOSE:-false}
 if [ "$verbose" != "false" ]; then
